name: Push to CDN

on:
  push:
    branches:
      - 'main'

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - name: Upload static files to CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamnks
          source: ./cdn
          destination: '/assets/'
      - run: 'echo "uploaded file ${{ steps.upload.outputs.uploaded }}"'